Feature python3
bepatient-fr/ikaaro pull request #19
Opened 2022-04-13 16:30 UTC by elterrien

code review

2022-04-15 14:30 UTC, M3te0r requested changes

2022-04-15 14:30 UTC, M3te0r commented on ikaaro/config_menu.py
> +    class_title = MSG('Men')
Petite typo : Menu

2022-04-15 14:30 UTC, M3te0r commented on ikaaro/context.py
> +            value, header_parameters = cgi.parse_header(content_disposition)
L'utilisation du module cgi m'étonne un peu, il n'y a pas de modules/utils plus "modernes"

2022-04-15 14:30 UTC, M3te0r commented on ikaaro/folder.py
> +                continue
logguer l'abspath pour identifier facilement et potentiellement supprimer les fichiers vides/corrompus

2022-04-15 14:30 UTC, M3te0r commented on ikaaro/server.py
> +            class_name = 'Root'
Même dans notre fork, le root BP ne devrait être hardcodé, mais provenir du fichier de conf

2022-04-19 09:25 UTC, elterrien commented on ikaaro/context.py
> +            value, header_parameters = cgi.parse_header(content_disposition)
Je n'ai pas trouvé d'alternatives. Par ailleurs, c'est le module utilisé par Django : https://github.com/django/django/blob/f4f2afeb457429f55d6325ed557f8e92a74ee028/django/http/request.py#L98

2022-04-19 09:30 UTC, M3te0r commented on ikaaro/context.py
> +            value, header_parameters = cgi.parse_header(content_disposition)
Ok, bien vu

2022-04-19 09:30 UTC, M3te0r approved these changes

2022-04-25 18:42 UTC, merged